# Generated by Django 5.1.6 on 2025-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/extra_images/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/extra_images/'),
        ),
    ]
