# Generated by Django 5.1.6 on 2025-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_institution_image_2_institution_image_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDefaultPlaceHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='DefaultPlaceHolder/')),
            ],
        ),
    ]
