# Generated by Django 5.1.6 on 2025-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_imagedefaultplaceholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='autres_informations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='horaires_ouverture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='informations_stationnement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='services_proposes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
