# Generated by Django 5.1.6 on 2025-02-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_institution_autres_informations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'activité")),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du service')),
            ],
        ),
        migrations.CreateModel(
            name='TypeLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='typelieu_images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Note')),
                ('localisation_image', models.ImageField(blank=True, null=True, upload_to='lieu_maps/', verbose_name='Image de la carte (Deuxième localisation)')),
                ('image_principale', models.ImageField(upload_to='lieu_images/', verbose_name='Image principale')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='lieu_images/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='lieu_images/', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='lieu_images/', verbose_name='Image 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='lieu_images/', verbose_name='Image 5')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('equipements', models.TextField(blank=True, null=True, verbose_name='Équipements')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('activites', models.ManyToManyField(blank=True, to='place.activite', verbose_name='Activités (pour endroits touristiques)')),
                ('services', models.ManyToManyField(blank=True, to='place.service', verbose_name='Services (pour hôtels)')),
                ('type_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.typelieu', verbose_name='Type de lieu')),
            ],
        ),
    ]
