# Generated by Django 5.1.6 on 2025-02-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_activite_service_typelieu_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='activites',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='services',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='type_lieu',
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Lieu',
        ),
        migrations.DeleteModel(
            name='TypeLieu',
        ),
    ]
