# Generated by Django 5.1.6 on 2025-02-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_remove_lieu_activites_remove_lieu_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='typelieu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('localisation', models.CharField(max_length=500)),
                ('image_principale', models.ImageField(upload_to='lieu_images/')),
                ('image2', models.ImageField(upload_to='lieu_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='lieu_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='lieu_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='lieu_images/')),
                ('image_localisation', models.ImageField(blank=True, null=True, upload_to='lieu_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('equipements', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('activites', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieux', to='place.typelieu')),
            ],
        ),
    ]
