# Generated by Django 5.1.6 on 2025-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_typelieu_lieu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lieu',
        ),
        migrations.DeleteModel(
            name='TypeLieu',
        ),
    ]
