# Generated by Django 5.1.6 on 2025-02-17 15:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_delete_lieu_delete_typelieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursismeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourisme_types/')),
            ],
        ),
        migrations.CreateModel(
            name='Toursisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('prix_par_nuit', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourisme/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='tourisme/extra_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='tourisme/extra_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='tourisme/extra_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='tourisme/extra_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('equipements', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.toursismetype')),
            ],
        ),
    ]
