# Generated by Django 5.1.6 on 2025-02-17 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_toursismetype_toursisme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireTourisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tourisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='place.toursisme')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
