# Generated by Django 5.1.6 on 2025-02-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_commentairetourisme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageDefaultPlaceHolder',
            new_name='DefaultPlaceHolderPersonne',
        ),
    ]
