# Generated by Django 5.1.6 on 2025-02-18 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_rename_imagedefaultplaceholder_defaultplaceholderpersonne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairetourisme',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentairetourisme',
            name='nom',
        ),
        migrations.AddField(
            model_name='commentairetourisme',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
