# Generated by Django 5.1.6 on 2025-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_remove_commentairetourisme_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentairetourisme',
            name='user',
        ),
        migrations.AddField(
            model_name='commentairetourisme',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='commentairetourisme',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
