# Generated by Django 5.1.6 on 2025-03-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
